name: build
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -Dwarnings
  DAYBREAK_BOT_TOKEN: ${{ secrets.DAYBREAK_BOT_TOKEN }}
  DAYBREAK_GUILD_ID: ${{ secrets.DAYBREAK_GUILD_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: shadowmoose/GHA-LoC-Badge@1.0.0
      with:
        directory: ./src/
        badge: ./.github/workflows/loc.svg
        patterns: '*.rs'
    
    - run: cargo build

    - name: Check format
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly
        cargo +nightly fmt --check
    
    - run: cargo doc --no-deps
    
    - run: cargo check
      
    - run: cargo clippy

    - run: cargo test
