name: build

on:
  - workflow_dispatch:
  - push:
    paths:
      - "src/**"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build

    - name: Check Format
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly
        cargo +nightly fmt --check

    - name: Lint with Rustc
      run: cargo check
      
    - name: Lint with Clippy
      run: cargo clippy

    - name: Run tests
      run: cargo test
